### ISSUE TITLE
initializer element is not constant

### ISSUE THREAD

**Issue by oldma3095** [asticode/go-astisrt#7]
static_consts.c

#include <srt/srt.h>

int32_t SRTGROUP_MASK_ = (1 << 30);
int SRT_LIVE_DEF_PLSIZE_ = 1316;
int SRT_LIVE_MAX_PLSIZE_ = 1456;
int SRT_LIVE_DEF_LATENCY_MS_ = 120;
SRTSOCKET SRT_INVALID_SOCK_ = -1;
int SRT_ERROR_ = -1;
int32_t SRT_SEQNO_NONE_ = -1;
int32_t SRT_MSGNO_NONE_ = -1;
int32_t SRT_MSGNO_CONTROL_ = 0;
int SRT_MSGTTL_INF_ = -1;
uint32_t SRT_GFLAG_SYNCONMSG_ = 1;

**Comment by asticode** [comment]
@oldma3095 can you describe your problem? I'm not getting it. Are you getting an error message? If so which `libsrt` are you using? On which OS? Or is it something entirely different?
